training:
  batch_size: 64
  num_epoches: 10
  learning_rate: 0.001
  optimizer: adam
  save_interval:

data:
  dataset: "mnist"
  data_dir: "./data"
  shuffle: true
  num_workers: 4

model:
  name: "simple_cnn"  # 可替换为 resnet等
  input_size: [1, 28, 28]
  num_classes: 10

logging:
  log_dir: "./outputs/logs"
  experiment_name: "mnist_experiment"